### ISSUE TITLE
Function definitions shouldn't use __attribute__((deprecated))

### ISSUE THREAD

**Issue by jrprice** [KhronosGroup/OpenCL-ICD-Loader#123]
The function definitions in the code generated for the ICD loader dispatch use the prefix/suffix preprocessor macros for marking APIs as deprecated. These macros potentially expand to include GCC's `__attribute__((deprecated))`, which isn't valid on function definitions. As noted in #122, this isn't an issue in practice for the ICD loader since we currently always support deprecated functions and therefore define the `CL_USE_DEPRECATED_OPENCL_*_APIS` macros that disable this.

**Comment by bashbaug** [comment]
OK, I think I see what's going on.  In short, prior to #114, most of the ICD loader dispatch functions (incorrectly) included the suffix macro on dispatch function definitions, but importantly there was no "deprecated" suffix macro on the OpenCL 2.x function definitions.  When the dispatch functions were generated in #114, the "deprecated" suffix macro got added, which exposed this problem.

I believe the fix is straightforward and is to omit the suffix macro from the function definitions.  The suffix macro should only be included in the function declarations, in the headers.  Note that we currently do not include the prefix macro in any of the function definitions.
