### ISSUE TITLE
Memory leak in icd.c

### ISSUE THREAD

**Issue by rlim77** [KhronosGroup/OpenCL-ICD-Loader#13]
Khronos ICD library do not free allocated memory at runtime. Our team discovered a memory leak with the ICD library. Appreciate it if this could be fixed.

\icd\icd.c
You need to add free in icd.c file, the numbers are the line numbers.
183 *prevNextPointer = vendor;
184 }
**185 free(vendor);
186 free(suffix);**
187 KHR_ICD_TRACE("successfully added vendor %s with suffix %s\n", libraryName, suffix);
188
189 }
190
191 Done:
192
193 if (library)
194

**Comment by MichaelE1000** [comment]
I don't think so. 

The allocated memory is added to a linked list called khrIcdVendors which is a linked list and presumably exists the whole time your application is up and running. If you look at the code there is also only a khrIcdInitialize initialize function but no way to free up the actual memory.

**Comment by kepatil** [comment]
Agree with @MichaelE1000. OpenCL API does not provide a clean deinitialization or exit point where to free these allocations. Using atexit() and similar hooks have ordering issues. I do not know of a good way to fix this apparent memory leak so it isn't going away anytime soon.

@rlim77 do you agree with the problem with your proposal? If you have another solution feel free to discuss. Otherwise I'm going to close this issue.

**Comment by rlim77** [comment]
Let me sync with our OCL team and get back to you.

Can I distill your response to mean that there's no good way to fix this?

**Comment by kepatil** [comment]
@rlim77 Yes, that's the summary.

**Comment by kepatil** [comment]
@rlim77, did you hear back from your team?

**Comment by rlim77** [comment]
I’m sorry. Yes. Please go ahead an close this. Thanks.
