### ISSUE TITLE
Failed to get number of platforms on Mac Intel and Mac M1

### ISSUE THREAD

**Issue by zchrissirhcz** [KhronosGroup/OpenCL-ICD-Loader#183]
Hi, OpenCL-ICD-Loader authors:

I'm using OpenCL-ICD-Loader and OpenCL-Headers on MacOSX, both Intel chip and M1. The OpenCL-ICD-Loader is the latest ([4aa6837](https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/4aa683775c4ee55594196c79def7a75103d75e4c)). 

The following code build OK, but running result is "failed to get number of platforms", which is not as expected.

And if I don't use OpenCL-ICD-Loader, use `find_package(OpenCL REQUIRED)` in CMakeLists.txt to find the system's OpenCL framework, the built program runs with expected result, i.e. number of platforms equal to 1.

```C++
#define CL_USE_DEPRECATED_OPENCL_1_2_APIS
#include <CL/opencl.h>

#include <stdio.h>

int main()
{
    cl_uint num_platforms;
    cl_int err = clGetPlatformIDs(0, NULL, &num_platforms);
    if (err != CL_SUCCESS)
    {
        printf("failed to get number of platforms");
        return 1;
    }
    printf("number of platforms: %u\n", num_platforms);

    return 0;
}
```

**Comment by bashbaug** [comment]
Hello!

This is the expected behavior: If you're trying to use the native MacOS OpenCL support (this is the common case) then you don't need this project (OpenCL-ICD-Loader) and you can link with the system's OpenCL framework to enumerate OpenCL platforms.  We do provide support for MacOS builds for uncommon cases that use the ICD extension and hence require an openCL ICD loader, such as [clvk](https://github.com/kpet/clvk) running on top of [MoltenVK](https://github.com/KhronosGroup/MoltenVK), but this is certainly uncommon.

Does this answer your question?  Thanks!

**Comment by zchrissirhcz** [comment]
Thank you for the detailed explanation.
