### ISSUE TITLE
Please add OpenCL.pc so pkg-config can find this package

### ISSUE THREAD

**Issue by CarterLi** [KhronosGroup/OpenCL-ICD-Loader#187]
Like what another repo did: https://github.com/OCL-dev/ocl-icd/blob/master/OpenCL.pc.in

Thanks.

**Comment by StuartDBrady** [comment]
See `gl.pc` on a typical distribution for an example of how this is done for GL, which typically has a dispatch layer similar to the ICD for OpenCL.  Note that there is a single libdir and includedir specified under a common pkgconfig file.  I would strongly recommend talking to package maintainers before doing otherwise for OpenCL.
