### ISSUE TITLE
Incorrect usage of LoadLibrary and string literal

### ISSUE THREAD

**Issue by michael-ashburn** [KhronosGroup/OpenCL-ICD-Loader#208]
Must be `LoadLibraryA("dll_name")` or `LoadLibrary(_T("dll_name"))`.

https://github.com/KhronosGroup/OpenCL-ICD-Loader/blob/2cde5d09953a041786d1cfdcb1c08704a82cb904/loader/windows/icd_windows.c#L276
https://github.com/KhronosGroup/OpenCL-ICD-Loader/blob/2cde5d09953a041786d1cfdcb1c08704a82cb904/loader/windows/icd_windows_dxgk.c#L38
https://github.com/KhronosGroup/OpenCL-ICD-Loader/blob/2cde5d09953a041786d1cfdcb1c08704a82cb904/loader/windows/icd_windows_apppackage.c#L42

**Comment by bashbaug** [comment]
Thanks for the report!

I think we're OK here in practice even if there could theoretically be a problem: because we don't define UNICODE for the OpenCL ICD loader `LoadLibrary` is equivalent to `LoadLibraryA`.

```c
#ifdef UNICODE
#define LoadLibrary  LoadLibraryW
#else
#define LoadLibrary  LoadLibraryA
#endif // !UNICODE
```

I'd be OK fixing this with either of the two solutions described above but I don't think this is super critical.

Are you aware of any need or desire to compile the ICD loader with UNICODE support?  If so, I'd be surprised if this were the only issue.

**Comment by michael-ashburn** [comment]
The issue is present in OpenCL.dll (MD5: 1aed9178389423caf14dadd8c232d2a7) from Intel CPU Runtime ver=2022.15.12.0.01 (https://github.com/intel/llvm/releases/download/2022-WW50/win-oclcpuexp-2022.15.12.0.01_rel.zip)

**Comment by bashbaug** [comment]
Sorry, I'm not following (my fault): What is "the issue" specifically in the DLL described above?

**Comment by michael-ashburn** [comment]
Caliing `LoadLibraryW` with ANSI string literal.
```
.text:00000001800075BD                 lea     rcx, aGdi32Dll  ; "gdi32.dll"
.text:00000001800075C4                 call    cs:LoadLibraryW
```
```
.text:0000000180007281                 lea     rcx, LibFileName ; "dxgi.dll"
.text:0000000180007288                 call    cs:LoadLibraryW
```
