### ISSUE TITLE
Error i stumbled upon 

### ISSUE THREAD

**Issue by LalleSX** [KhronosGroup/OpenCL-ICD-Loader#223]
While building [MinecraftC](https://github.com/johnpayne-dev/MinecraftC/tree/main) i got an error that said the file located at ```loader/linux/icd_linux_envvars.c``` saying that line 24 
```c
#include icd_cmake_config.h
``` 
didn't exist, while tweaking around Copilot changed the line to be

 ```c
#include "icd.h"
```
instead and that removed the errors that VsCode showed and made it so i could build the project.

I am just reporting this incident i know nothing about ICD's or OpenCL for that matter. I hope this helped :D

**Comment by bashbaug** [comment]
Hi, thanks for filing this issue!

I had a look at the MinecraftC project and I think I can explain what is happening here.  In short, it's a neat project, but it appears to be use the OpenCL ICD loader in a bit of a weird way - instead of using the OpenCL ICD loader CMake files to build a library to link to, MinecraftC adds the OpenCL ICD loader source files directly and builds them as part of its executable.  This causes it to bypass creation of `icd_cmake_config.h`, ultimately leading to the build error.

Because `icd_cmake_config.h` really only stores the results of detection for different secure `getenv` functions, and because we have fallback paths when no secure `getenv` functions are found, the project will build if the include file is omitted entirely, albeit with a warning:

```sh
note: ‘#pragma message: Warning:  Falling back to non-secure getenv for environmental lookups!  Consider updating to a different libc.’
```

I don't think this usage is one we want to encourage, and none of this should be an issue if the OpenCL ICD loader is used in more conventional ways (such as those used by the [OpenCL-SDK](https://github.com/KhronosGroup/OpenCL-SDK/)), so I think we're likely to close this issue with no changes.  Make sense?

Thanks again!
