### ISSUE TITLE
Building with 2.0 Headers

### ISSUE THREAD

**Issue by SiggyFPGA** [KhronosGroup/OpenCL-ICD-Loader#24]
Hey all,
I need to compile the ICD Loader / OpenCL libraries using 2.0 headers. When I do it, the compiler complains about not finding "CL_API_SUFFIX__VERSION_2_2" for the dispatcher. Is there any compiler flag / define, that I can use to exclude 2.2 and 2.1 features? The sources for the 2.0 ICD Loader, would also help. Can they be found somewhere on the Web? Going back in the commits of this project, I only get to Version 2.1. I also found this Open Source project: https://github.com/OCL-dev/ocl-icd, but it would be nice to have a clean Khronos solution.

Thanks,
Siggy

**Comment by kepatil** [comment]
I understand your issue but please help me understand your use case better. What is preventing you from using the latest headers to build the ICD loader?

Currently there is no way to limit the ICD loader to a particular OpenCL API version. When we (Khronos) released the ICD loader source we had discussed that since the ICD loader was fully backwards compatible everyone can use the latest ICD version (built with the latest version of CL headers). That simplifies things quite a bit because we have to maintain only one source tree.

**Comment by SiggyFPGA** [comment]
The problem with my headers is, that there have been some changes made to it. So I can't just grab the newest header version from khronos, as there would be some content missing.

**Comment by kepatil** [comment]
Can you explain what changes you have made to the headers? Usually the headers are meant to be used without any change. If there is any issue with the headers then I would like to know and fix it.

**Comment by SiggyFPGA** [comment]
I will try to fix the issues myself. If any problem occur concerning the ICD loader, I will open a new issue specifically targeting that problem. Thanks for your fast replies and great help.
