### ISSUE TITLE
Some bugs encountered while building with VS 2017 64bit

### ISSUE THREAD

**Issue by SilverCamel** [KhronosGroup/OpenCL-ICD-Loader#38]
1. The file 'test/loader_test/test_create_calls.c' needs #include <stdlib.h>', needed by the 'malloc' function, otherwise 'write access violation' error is given.

2. In the file 'test/driver_stub/cl.c', at line no. 510 for the function call 'test_icd_stub_log("clCreateImage2D(' the eighth parameter 'errcode_ret' is missing.

**Comment by kepatil** [comment]
@SilverCamel Can you please create a pull request for this? The proposed fixes sound good.

**Comment by SilverCamel** [comment]
Hello kepatil,

I am new to Github, I only joined it today.  Can you please tell how to go about making a pull request and what purpose does it solve. Thanks.

regards

**Comment by kepatil** [comment]
A pull request will let me see the exact change you want to make to the source code. I will then be able to review and accept your contribution.

Pull requests are explained at https://help.github.com/articles/creating-a-pull-request/.

Since you do not have write permissions on this project repository you will need to follow the fork-and-pull model. See https://guides.github.com/activities/forking/.

**Comment by SilverCamel** [comment]
Hello kepatil,

I have made a pull request for the aforementioned topic. Please check. Thanks.

regards

**Comment by bashbaug** [comment]
Since pull request #39 has been merged, can this issue be closed?  Thanks!

**Comment by kepatil** [comment]
Ah, thanks for the reminder! Closing.
