### ISSUE TITLE
compile error file missing

### ISSUE THREAD

**Issue by eribell** [KhronosGroup/OpenCL-ICD-Loader#49]
/home/user/Desktop/OpenCL-ICD-Loader/icd.h:53:10: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
          ^~~~~~~~~

**Comment by trecakov** [comment]
@eribell Check this, it may help.
https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/10

**Comment by bashbaug** [comment]
Hi @eribell,

We've made a lot of enhancements to the README to describe the build process in more detail since you've filed this issue.  We've also enabled CI builds via Travis CI and you may find it helpful to look at the [Travis CI config file](https://github.com/KhronosGroup/OpenCL-ICD-Loader/blob/master/.travis.yml) to see what commands it uses to build.

I believe the information above is sufficient to close this issue, but please feel free to re-open it if you are still having build problems.  Thanks!
